### PR TITLE
keep track of headers complete

### PR DESCRIPTION
**Pull request by jessberg**
This keeps track of RPCs' headers as they go in and out of the node, so we can propagate our custom headers in the simulator.

### CODE REVIEW

**Comment by fruffy** [comment]
Shouldn't this be part of the filter state?
This is how its done in the cpp filter:
```cc
void BidiContext::onResponseHeadersOutbound() {
    // Received response from another service we called.
    // Collect x-wasm header value.
    auto header = getResponseHeader("x-wasm");
    if (header->data() != nullptr) {
        WasmDataPtr shared_data;
        WasmResult result = getSharedData(b3_trace_id_ + "path", &shared_data);
        if (result == WasmResult::Ok && shared_data->data() != nullptr) {
            LOG_WARN("Merging path x-wasm: " + shared_data->toString() + "," +
                     header->toString());
            setSharedData(b3_trace_id_ + "path",
                          shared_data->toString() + "," + header->toString());
        } else {
            LOG_WARN("Setting x-wasm: " + header->toString());
            setSharedData(b3_trace_id_ + "path", header->toString());
        }
    } else {
        LOG_WARN("x-wasm not found");
    }

    auto property_header = getResponseHeader("x-wasm-property");
    if (property_header->data() != nullptr) {
        WasmDataPtr shared_data;
        WasmResult result =
            getSharedData(b3_trace_id_ + "property", &shared_data);
        if (result == WasmResult::Ok && shared_data->data() != nullptr) {
            LOG_WARN("Merging x-wasm-property: " + shared_data->toString() + "," +
                     property_header->toString());
            setSharedData(b3_trace_id_ + "property",
                          shared_data->toString() + "," +
                              property_header->toString());
        } else {
            LOG_WARN("Setting x-wasm-property: " + header->toString());
            setSharedData(b3_trace_id_ + "property",
                          property_header->toString());
        }
    } else {
        LOG_WARN("x-wasm-property not found");
    }
}
```

**Comment by jessberg** [comment]
> Shouldn't this be part of the filter state?
> This is how its done in the cpp filter:
> 
> ```c++
> void BidiContext::onResponseHeadersOutbound() {
>     // Received response from another service we called.
>     // Collect x-wasm header value.
>     auto header = getResponseHeader("x-wasm");
>     if (header->data() != nullptr) {
>         WasmDataPtr shared_data;
>         WasmResult result = getSharedData(b3_trace_id_ + "path", &shared_data);
>         if (result == WasmResult::Ok && shared_data->data() != nullptr) {
>             LOG_WARN("Merging path x-wasm: " + shared_data->toString() + "," +
>                      header->toString());
>             setSharedData(b3_trace_id_ + "path",
>                           shared_data->toString() + "," + header->toString());
>         } else {
>             LOG_WARN("Setting x-wasm: " + header->toString());
>             setSharedData(b3_trace_id_ + "path", header->toString());
>         }
>     } else {
>         LOG_WARN("x-wasm not found");
>     }
> 
>     auto property_header = getResponseHeader("x-wasm-property");
>     if (property_header->data() != nullptr) {
>         WasmDataPtr shared_data;
>         WasmResult result =
>             getSharedData(b3_trace_id_ + "property", &shared_data);
>         if (result == WasmResult::Ok && shared_data->data() != nullptr) {
>             LOG_WARN("Merging x-wasm-property: " + shared_data->toString() + "," +
>                      property_header->toString());
>             setSharedData(b3_trace_id_ + "property",
>                           shared_data->toString() + "," +
>                               property_header->toString());
>         } else {
>             LOG_WARN("Setting x-wasm-property: " + header->toString());
>             setSharedData(b3_trace_id_ + "property",
>                           property_header->toString());
>         }
>     } else {
>         LOG_WARN("x-wasm-property not found");
>     }
> }
> ```

What do you mean?  In the C++ filter we use getSharedData.  We have no such function in the simulator so there is just an extra field on the filter, so it is part of the filter's state.

**Comment by fruffy** [comment]
Don't we have filter_state? Isn't that the same as the shared data in Envoy?

**Comment by jessberg** [comment]
> Don't we have filter_state? Isn't that the same as the shared data in Envoy?

Shared state is meant to be different envoy properties, eg, name.metadata.WORKLOAD_NAME.  If it is managed by envoy, we could put it in the same hashmap, and change it to everything that is managed by envoy.  Is that what you'd suggest?

**Comment by fruffy** [comment]
Hmm I do not know if the envoy properties and proxy_get_shared_data access the same data store. We can make it separate then, but shared_data should just be a String hashmap then.

**Comment by fruffy** [comment]
Btw the udfs also will have to use shared_data then

**Comment by jessberg** [comment]
Shouldn't shared data also contain the UID, so it should be a u64 to a String hashmap?  And the UDFs don't store any data locally on the filter - the result of the UDF is put into baggage.

**Comment by fruffy** [comment]
No, shared_data can be anything it is a HashMap<String, String>. 
I am fine with the UDF baggage computation, but that implies the C++ UDFs will have to change since they store state locally.

**Comment by jessberg** [comment]
> No, shared_data can be anything it is a HashMap<String, String>.
> I am fine with the UDF baggage computation, but that implies the C++ UDFs will have to change since they store state locally.

Okay so then when we actually store headers in there it should come out like uid_as_string -> [header_name] [separator] [header_value].  And then if we find other uses for shared data, we can use the same store.

I think the C++ UDFs will have to change, but a lot about the C++ version is going to have to change, so I think it might be a good idea to just get one version working first.

**Comment by fruffy** [comment]
Well it essentially just the baggage that has to be merged. If you look at the C++ code I posted it provides a good outline x-wasm is the tree, and x-wasm-property is the "baggage" with various items in it. Do not really know how we want to define baggage yet. I guess having a header per property is fine. It should not make much of a difference.

**Review by fruffy — APPROVED** [review]

**Pull request merged**
