### PR TITLE
Envoy aggregation

### PR DESCRIPTION
**Pull request by jessberg**
This implements aggregation functions.  They are separate filters, and exist in the aggregation_filter_envoy folder.  I tried to put them in the same folder as filter_envoy, but that had issues because they had the same start functions.  In any case, they are separate filters so I think it makes sense to maintain them separately.  A working example of a query for this is height_avg.cql.

As far as the functionality goes, there's nothing too complicated.  The filters keep aggregation UDFs in their shared storage, and take them out and perform an execute function with the inputs in incoming requests.  Then the filter manipulates the incoming request to output the UDF name and value instead of its original value.  If there are no UDFs, this is simply a blank and useless filter.

### CODE REVIEW

**Comment by fruffy** [comment]
> but that had issues because they had the same start functions.
That usually indicates incorrect compilation you need to compile with `cargo +nightly build --target=wasm32-unknown-unknown --release`

**Comment by jessberg** [comment]
> > but that had issues because they had the same start functions.
> 
> That usually indicates incorrect compilation you need to compile with `cargo +nightly build --target=wasm32-unknown-unknown --release`

Yes, I used that I believe because I used the build script inside filter_envoy.  The error was 


error: symbol `_start` is already defined
   --> filter_base.rs:183:1
    |
183 | pub fn _start() {
    | ^^^^^^^^^^^^^^^

**Comment by fruffy** [comment]
Rust is very awkward when it comes to this but it is solvable. I have a solution that minimizes the amount of duplicate dependencies etc.. Also makes it possible to reuse filter base, if needed.
I took the liberty to push a proposal. Feel free to revert it, but I think helps in unifying things. To produce the filters you just need to compile with `cargo +nightly build -Z unstable-options --target=wasm32-unknown-unknown --release --out-dir wasm_bins --target-dir target` for the main filter and 
`cargo +nightly build -Z unstable-options --target=wasm32-unknown-unknown --release --out-dir wasm_bins --target-dir target --manifest-path agg/Cargo.toml` for the aggregation filter. Now both share dependencies, do not duplicate the target folder, and also emit a wasm file into a dedicated folder. This makes things a bit easier on the tracing_env side.

**Comment by jessberg** [comment]
This looks great!  Just one thing - is it already implemented for the distributed filter, or it just can be done?  The script for the distributed filter looks the same.

**Comment by fruffy** [comment]
I did not merge the distributed filter in, that requires more work it seems. Currently, everything is copied as usual. It would be nice if the distributed filter could also be part of the envoy folder. I also pushed something to tracing env, there it seems to pass all tests.

**Review by fruffy — APPROVED** [review]

**Pull request merged**
